import { Component } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';

@Component({
  selector: 'app-customer-data',
  templateUrl: './customer-data.component.html',
  styleUrls: ['./customer-data.component.scss']
})
export class CustomerDataComponent {
  addressForm = this.fb.group({
    firstName: [null, Validators.required],
    lastName: [null, Validators.required],
    address: [null, Validators.required],
    city: [null, Validators.required],
    state: [null, Validators.required],
    postalCode: [null, Validators.required],
    phone: [null, Validators.required],
    shipping: ['free', Validators.required]
  });

  states = [
    {name: 'A. Gonzalez Chavez'},
    {name: 'Arrecifes'},
    {name: 'Bahia Blanca'},
    {name: 'Berazategui'},
    {name: 'Brandsen'},
    {name: 'Buenos Aires CABA'},
    {name: 'Carlos Casares'},
    {name: 'Chacabuco'},
    {name: 'Coronel Dorrego'},
    {name: 'Daireaux'},
    {name: 'Escobar'},
    {name: 'Florencio Varela'},
    {name: 'General Arenales'},
    {name: 'General Las Heras'},
    {name: 'General Pinto'},
    {name: 'General Viamonte'},
    {name: 'Hurlingham'},
    {name: 'La Matanza'},
    {name: 'Las Flores'},
    {name: 'Lobos'},
    {name: 'Maipu'},
    {name: 'Mercedes'},
    {name: 'Moreno'},
    {name: 'Nueve De Julio'},
    {name: 'Pellegrini'},
    {name: 'Pinamar'},
    {name: 'Quilmes'},
    {name: 'Rojas'},
    {name: 'Salliquelo'},
    {name: 'San Cayetano'},
    {name: 'San Nicolas'},
    {name: 'Tandil'},
    {name: 'Tornquist'},
    {name: 'Tres Lomas'},
    {name: 'Villarino'},
    {name: 'Leandro N. Alem'},
    {name: 'Loberia'},
    {name: 'Lomas De Zamora'},
    {name: 'Magdalena'},
    {name: 'Malvinas Argentinas'},
    {name: 'Marcos Paz'},
    {name: 'Merlo'},
    {name: 'Monte Hermoso'},
    {name: 'Moron'},
    {name: 'Necochea'},
    {name: 'Olavarria'},
    {name: 'Pehuajo'},
    {name: 'Pergamino'},
    {name: 'Pilar'},
    {name: 'Presidente Peron'},
    {name: 'Punta Indio'},
    {name: 'Ramallo'},
    {name: 'Rivadavia'},
    {name: 'Roque Perez'},
    {name: 'Saladillo'},
    {name: 'Salto'},
    {name: 'San Antonio De Areco'},
    {name: 'San Fernando'},
    {name: 'San Miguel'},
    {name: 'San Pedro'},
    {name: 'Suipacha'},
    {name: 'Tapalque'},
    {name: 'Tordillo'},
    {name: 'Trenque Lauquen'},
    {name: 'Tres De Febrero'},
    {name: 'Veinticinco De Mayo'},
    {name: 'Villa Gesell'},
    {name: 'Zarate'},
    {name: 'Las Flores'},
    {name: 'Lincoln'},
    {name: 'Lobos'},
    {name: 'Lujan'},
    {name: 'Maipu'},
    {name: 'Mar Chiquita'},
    {name: 'Mercedes'},
    {name: 'Monte'},
    {name: 'Moreno'},
    {name: 'Navarro'},
    {name: 'Nueve De Julio'},
    {name: 'Patagones'},
    {name: 'Pellegrini'},
    {name: 'Pila'},
    {name: 'Pinamar'},
    {name: 'Puan'},
    {name: 'Quilmes'},
    {name: 'Rauch'},
    {name: 'Rojas'},
    {name: 'Saavedra'},
    {name: 'Salliquelo'},
    {name: 'San Andres De Giles'},
    {name: 'San Cayetano'},
    {name: 'San Isidro'},
    {name: 'San Nicolas'},
    {name: 'San Vicente'},
    {name: 'Tandil'},
    {name: 'Tigre'},
    {name: 'Tornquist'},
    {name: 'Tres Arroyos'},
    {name: 'Tres Lomas'},
    {name: 'Vicente Lopez'},
    {name: 'Villarino'},
    {name: 'Ramallo'},
    {name: 'Rivadavia'},
    {name: 'Roque Perez'},
    {name: 'Saladillo'},
    {name: 'Salto'},
    {name: 'San Antonio De Areco'},
    {name: 'San Fernando'},
    {name: 'San Miguel'},
    {name: 'San Pedro'},
    {name: 'Suipacha'},
    {name: 'Tapalque'},
    {name: 'Tordillo'},
    {name: 'Trenque Lauquen'},
    {name: 'Tres De Febrero'},
    {name: 'Veinticinco De Mayo'},
    {name: 'Villa Gesell'},
    {name: 'Zarate'},
    {name: 'Suipacha'},
    {name: 'Tapalque'},
    {name: 'Tordillo'},
    {name: 'Trenque Lauquen'},
    {name: 'Tres De Febrero'},
    {name: 'Veinticinco De Mayo'},
    {name: 'Villa Gesell'},
    {name: 'Zarate'},
    {name: 'Tres Lomas'},
    {name: 'Vicente Lopez'},
    {name: 'Villarino'},
    {name: 'Villa Gesell'},
    {name: 'Zarate'},
  ];

  constructor(private fb: FormBuilder) {}

  onSubmit() {
    alert('Thanks!');
    this.addressForm.reset();

  }
}

